# Generated by Django 6.0.2 on 2026-03-05 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_profile_avatar_remove_profile_loyalty_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='client_name',
        ),
    ]
