# Generated by Django 6.0.2 on 2026-03-09 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_profile_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, unique=True)),
                ('items', models.JSONField(default=list)),
                ('services', models.JSONField(default=list)),
                ('branches', models.JSONField(default=list)),
                ('image_url', models.URLField(blank=True, default='')),
            ],
        ),
    ]
